### ISSUE TITLE
[Issue] Error in VsCode for every external package imports (like @openzeppelin for instance)

### ISSUE THREAD

**Issue by ebouchut** [bet-no-loss/bet-no-loss#31]
## Description 

> In **VsCode**, when I opening a smart-contract that imports a  file from a npm package
> then the editor displays an error for every import of an external module (like @openzeppelin imports for instance)
> saying for instance in the `Bet.sol` contract , 
> Source "/Users/eric/dev/alyra/project/bet-no-loss/contracts/@openzeppelin/contracts/access/Ownable.sol" not found: File import callback not supported

## Context

- `truffle-config.json` is configured to store contracts JSON ABI in `client/src/contracts`
```
module.exports = {
  contracts_build_directory: path.join(__dirname, "client/src/contracts")
  ...
}
```

- VsCode
    - **Configuration** (default)
        -  `"packageDefaultDependenciesContractsDirectory": ''`
        -  `"packageDefaultDependenciesDirectory":  'node_modules'`
    - Version: 1.55.0
    - Commit: c185983a683d14c396952dd432459097bc7f757f
    - Date: 2021-03-30T16:01:05.981Z
    - Electron: 11.3.0
    - Chrome: 87.0.4280.141 
    - Node.js: 12.18.3
    - V8: 8.7.220.31-electron.0
    - OS: Darwin x64 18.7.0
- node version: v15.13.0
- npm version: 7.7.6

## How to Reproduce the Issue

- Launch VsCode and open the bet-no-loss project
- Open the file `contracts/Bet.sol` 

## Expected Result
The `@openzeppelin` imports should not be marked as errors (in red)

## Actual Result
The `@openzeppelin` imports are marked as errors
<img width="503" alt="vscode-import-error-1" src="https://user-images.githubusercontent.com/73331/113765131-2cb6fb80-971c-11eb-8076-ee7266739711.png">
<img width="1085" alt="vscode-solidity-import-error-2" src="https://user-images.githubusercontent.com/73331/113765137-2d4f9200-971c-11eb-922b-2abfd85aedae.png">

**Comment by ebouchut** [comment]
We are not alone, see: https://github.com/juanfranblanco/vscode-solidity/issues/149

**Comment by Tanteli** [comment]
Got the same issue. I fixed it by selecting the release that is the same as set in the dependencies in the package.json.

![image](https://user-images.githubusercontent.com/33956746/113782642-d608ec00-9732-11eb-98a1-58cdd160bbe7.png)

**Comment by ebouchut** [comment]
Thx @Tanteli, 
I had a workspace composed of multiple git repositories/projects.
As of now, my understanding is that was causing the issue.

Workaround: I closed the workspace and solely opened the **project's folder** which removed the warnings.
