### ISSUE TITLE
Init & configure project

### ISSUE THREAD

**Issue by Tanteli** [bet-no-loss/bet-no-loss#4]
## Description 

> Bootstrap the whole project and make the configurations needed

- Install `truffle unbox react`
- Create a new **Ganache workspace**
- Modify `truffle-config.js` related to Ganache configuration:
    - `host`
    - `port`
    - `network_id`
- Use `dotenv` npm package and store the following properties in the `.env` file in the project's root directory:
    - 12 words wallet seed passphrase (`MNEMONIC`)
    - Infura project id (`INFURA_PROJECT_ID`)

**Comment by ebouchut** [comment]
Use **7546** as **Ganache workspace port number**.

**Comment by ebouchut** [comment]
Added a section on **[How to configure Ganache](https://github.com/bet-no-loss/bet-no-loss/wiki/DevConfig#ganache)** in the **wiki**.

**Comment by ebouchut** [comment]
Seems like the automation was not up to par on this one.
Closing it manually.
