### ISSUE TITLE
[Contract] ERC-20 Token Management

### ISSUE THREAD

**Issue by Tanteli** [bet-no-loss/bet-no-loss#6]
## Description 

> Manage the smart contract to receive and transfer ERC-20 related tokens

## Details
- the contract could receive ERC-20 tokens from another address
- the contract could transfer tokens to another address
- users could deposit ERC-20 tokens on the contract
- users could withdraw their ERC-20 tokens

**Comment by ebouchut** [comment]
How about restricting the ERC-20 token to only DAI for now?
